name: ci

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
  pull_request:
    paths:
      - "app/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run fmt
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test
