on:
  push:
    branches:
      - main
    paths:
      - "lambda-image/src/**"
  pull_request:
    paths:
      - "lambda-image/src/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda-image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup dependencies
        run: npm ci

      - name: Lint
        run: npm run check

      - name: Test
        run: npm run test -- run

      - name: Build
        run: npm run build
