name: ci_spot_task_image

on:
  push:
    branches:
      - main
    paths:
      - "lambda-images/src/spot-task/**"
      - "lambda-images/src/shared/**"
  pull_request:
    paths:
      - "lambda-images/src/spot-task/**"
      - "lambda-images/src/shared/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda-images

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup dependencies
        run: npm ci

      - name: Lint
        run: npm run check

      - name: Test
        run: npm run test -- run

      - name: Build
        run: npm run build:spot-task
