on:
  push:
    branches:
      - main
    paths:
      - "lambda-images/src/spot-task/**"
      - "lambda-images/src/shared/**"

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda-images
    timeout-minutes: 300
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::540093229923:role/podcast-lambda-repository-role

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: podcast-lambda-spot-task-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -f spotTask.Dockerfile --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }} --all-tags

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Update Lambda function
        env:
          FUNCTION_NAME: podcast-lambda-spot-task
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: podcast-lambda-spot-task-repository
          IMAGE_TAG: ${{ github.sha }}
        run: aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME}} --image-uri ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
